config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, except: [:destroy, :update] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail_id, uniqueness: {scope: :ingredient_id}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
before_action :set_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
  end

  def create
     @dose = Dose.new(dose_params)
     @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

   def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>


  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/cocktails/index.html.erb
<%= render "layouts/navbar" %>
<br>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://cdn.liquor.com/wp-content/uploads/2015/03/hub_classic_cocktail_daiquiri.jpg');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2><%= cocktail.name %></h2>
        </div>
        <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
      </div>
    </div>
    <% end %>
  </div>
</div>


<%= link_to "Add a cocktail", new_cocktail_path, class: 'btn btn-outline-secondary', role: 'button' %>
<!-- <button type="button" class="btn btn-outline-secondary">Secondary</button> -->

app/views/cocktails/new.html.erb
<%= render "layouts/navbar" %>
<%= render 'cocktails/form', cocktail: @cocktail  %>

app/views/cocktails/show.html.erb
<%= render "layouts/navbar" %>
<h1><%= @cocktail.name %></h1>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li>
     <%= dose.ingredient.name %> | <%= dose.description  %>
     | <%= link_to "Delete", dose_path(dose), method: :delete %>

    </li>
  <% end %>
</ul>
<%= link_to "Add a Dose", new_cocktail_dose_path(@cocktail) %>
<%= link_to "Back to Cocktails", cocktails_path %>

app/views/doses/new.html.erb
<%= render "layouts/navbar" %>
<h3>Add a dose</h3>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "COCKTAIL HUB", cocktails_path, class: 'navbar-wagon-brand' %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Add a Cocktail", new_cocktail_path, class: 'navbar-wagon-item navbar-wagon-link'  %>

    <!-- Profile picture with dropdown list -->
    <!-- <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div> -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>